name: Build & Push (GHCR) - ga_influxdbv1

on:
  push:
    branches: [ main ]
    paths:
      - "influxdb/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NS: ghcr.io/greenautarky
  ADDON_SLUG: ga_influxdbv1
  ADDON_DIR: influxdb
  BASE_VERSION: v8.1.3   # hassio-addons/debian-base tag

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ha_arch: aarch64
            platform: linux/arm64
          - ha_arch: amd64
            platform: linux/amd64
          - ha_arch: armv7
            platform: linux/arm/v7
          # Uncomment if you really need them and the base exists for this version:
          # - ha_arch: armhf
          #   platform: linux/arm/v6
          # - ha_arch: i386
          #   platform: linux/386

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ... keep your existing 'env', 'matrix', and steps above ...

      - name: Read add-on version from config.yaml
        id: ver
        shell: bash
        run: |
          ver=$(grep -E '^version:' "${{ env.ADDON_DIR }}/config.yaml" | head -n1 | awk '{print $2}' | tr -d '"')
          if [ -z "$ver" ]; then
            echo "Could not read version from config.yaml" >&2
            exit 1
          fi
          echo "value=$ver" >> "$GITHUB_OUTPUT"

      - name: Metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NS }}/${{ env.ADDON_SLUG }}-${{ matrix.ha_arch }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.ver.outputs.value }}
            # optional: also tag on git tags like v0.0.1
            type=ref,event=tag
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Resolve base image
        id: base
        shell: bash
        run: |
          case "${{ matrix.ha_arch }}" in
            armv7)
              echo "img=ghcr.io/hassio-addons/debian-base/armv7:7.8.1" >> "$GITHUB_OUTPUT"
              ;;
            aarch64|amd64)
              echo "img=ghcr.io/hassio-addons/debian-base/${{ matrix.ha_arch }}:${{ env.BASE_VERSION }}" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "Unsupported arch: ${{ matrix.ha_arch }}" >&2
              exit 1
              ;;
          esac
          echo "Using base: $(sed -n 's/^img=//p' "$GITHUB_OUTPUT")"

      - name: Build & Push (${{ matrix.ha_arch }})
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.ADDON_DIR }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=${{ steps.base.outputs.img }}
            BUILD_ARCH=${{ matrix.ha_arch }}


