name: Build & Push (GHCR) - ga_influxdbv1

on:
  push:
    branches: [ main ]
    paths:
      - "influxdb/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NS: ghcr.io/greenautarky
  ADDON_SLUG: ga_influxdbv1
  ADDON_DIR: influxdb
  BASE_VERSION: v8.1.1   # <- correct current tag for aarch64/amd64

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ha_arch: aarch64
            platform: linux/arm64
          - ha_arch: amd64
            platform: linux/amd64
          - ha_arch: armv7
            platform: linux/arm/v7

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Read add-on version from influxdb/config.yaml (supports quoted/unquoted, ignores comments)
      - name: Read add-on version
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          f="${{ env.ADDON_DIR }}/config.yaml"
      
          echo ">>> Looking for 'version:' in $f"
          # Show any version lines (for debugging)
          grep -n -i '^[[:space:]]*version[[:space:]]*:' "$f" || true
      
          # Robust extract: take the first 'version:' key, strip comments/quotes/space
          ver=$(
            awk 'BEGIN{IGNORECASE=1}
              /^[[:space:]]*version[[:space:]]*:/{
                sub(/^.*version[[:space:]]*:[[:space:]]*/,"");  # drop key and colon
                sub(/[[:space:]]*#.*/,"");                      # drop trailing comment
                gsub(/"/,"");                                   # drop quotes
                gsub(/[[:space:]]/,"");                         # drop spaces/tabs
                print; exit
              }' "$f"
          )
      
          if [ -z "${ver:-}" ]; then
            echo "::error::Could not read version from $f"
            echo "First 30 lines for inspection:"; nl -ba "$f" | sed -n '1,30p'
            exit 1
          fi
      
          echo "Detected add-on version: $ver"
          echo "value=$ver" >> "$GITHUB_OUTPUT"

      - name: Metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NS }}/${{ env.ADDON_SLUG }}-${{ matrix.ha_arch }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.ver.outputs.value }}
            type=ref,event=tag
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Resolve base image
        id: base
        shell: bash
        run: |
          case "${{ matrix.ha_arch }}" in
            armv7)
              echo "img=ghcr.io/hassio-addons/debian-base/armv7:7.8.1" >> "$GITHUB_OUTPUT"
              ;;
            aarch64|amd64)
              echo "img=ghcr.io/hassio-addons/debian-base/${{ matrix.ha_arch }}:${{ env.BASE_VERSION }}" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "Unsupported arch: ${{ matrix.ha_arch }}" >&2
              exit 1
              ;;
          esac
          echo "Using base: $(sed -n 's/^img=//p' "$GITHUB_OUTPUT")"

      - name: Build & Push (${{ matrix.ha_arch }})
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.ADDON_DIR }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=${{ steps.base.outputs.img }}
            BUILD_ARCH=${{ matrix.ha_arch }}
