name: Build & Push (GHCR) - ga_influxdbv1

on:
  push:
    branches: [ main ]
    paths:
      - "influxdb/**"
      - ".github/workflows/publish.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NS: ghcr.io/greenautarky
  ADDON_SLUG: ga_influxdbv1
  ADDON_DIR: influxdb
  BASE_VERSION: v8.1.3   # hassio-addons/debian-base tag

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ha_arch: aarch64
            platform: linux/arm64
          - ha_arch: amd64
            platform: linux/amd64
          - ha_arch: armv7
            platform: linux/arm/v7
          # Uncomment if you really need them and the base exists for this version:
          # - ha_arch: armhf
          #   platform: linux/arm/v6
          # - ha_arch: i386
          #   platform: linux/386

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NS }}/${{ env.ADDON_SLUG }}-${{ matrix.ha_arch }}
          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=sha,format=short
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & Push (${{ matrix.ha_arch }})
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.ADDON_DIR }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/debian-base/${{ matrix.ha_arch }}:${{ env.BASE_VERSION }}
            BUILD_ARCH=${{ matrix.ha_arch }}
            BUILD_VERSION=${{ github.ref_name }}
            BUILD_DATE=${{ github.sha }}
